### ISSUE TITLE
is unverified and has been removed from the bot list

### ISSUE THREAD

**Issue by irritability** [mb-1337/OpenDiscordHaxx#1]
Keep getting the Error "is unverified and has been removed from the bot list" Not sure why when they all are verified bots via email?
![0n7rhif](https://user-images.githubusercontent.com/48553830/118346815-2cc0cd00-b50c-11eb-919f-7e10974c28dd.png)

**Comment by mb-1337** [comment]
That error usually means the tokens are invalid, but in your case it's something else and I cannot be bothered to fix it; nobody uses the tool and honestly I lost the motivation and hope for this project. Will discontinue soon, have a nice day!
